version: '3.7'

services:

  imprensa:
    container_name: imprensa
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8003:8080'